---
title: "Introduction to _R_ and _Bioconductor_"
author:
- name: Martin Morgan
  affiliation: Roswell Park Comprehensive Cancer Center
date: "`r format(Sys.time(), '%B %d, %Y')`"
vignette: >
  %\VignetteIndexEntry{01: Introdction to R and Bioconductor}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
  BiocStyle::html_document:
    number_sections: yes
    toc: true
---

Last modified: 23 June, 2019

```{r style, echo = FALSE, results = 'asis'}
knitr::opts_chunk$set(
    eval=as.logical(Sys.getenv("KNITR_EVAL", "TRUE")),
    cache=as.logical(Sys.getenv("KNITR_CACHE", "TRUE"))
)
options(width = 75)
```

# _R_

## Vectors

'atomic' types

lists

Trouble!

- `NA`

- Factors

## Objects

```{r}
x <- rnorm(100)
hist(x)
y <- x + rnorm(100)
df <- data.frame(x, y)
plot(y ~ x, df)
fit <- lm(y ~ x)
summary(fit)
abline(fit)
```

## Packages

```{r, messgae = FALSE}
library(ggplot2)
```

```{r}
ggplot(df, aes(x, y)) + 
    geom_point() +
    geom_smooth(method="lm")
```

## 'Tidy' data

```{r, message = FALSE}
library(dplyr)
library(tibble)
library(tidyr)
```

# Bioconductor

```{r, message = FALSE}
library(Biostrings)
```

```{r}
seq = c("AAACA", "CATGC")
dna <- DNAStringSet(seq)
reverseComplement(dna)
```

```{r, message = FALSE}
library(BSgenome)
library(BSgenome.Hsapiens.UCSC.hg38)
```

## What's available?

Web site

Support site

slack

## Installing software

```{r, message = FALSE}
library(BiocManager)
```

```{r}
BiocManager::available("BSgenome")
```

```{r, eval=FALSE}
## also possible to install CRAN, github packages
BiocManager::install("BSgenome.Hsapiens.UCSC.hg38")
```

# Provenance

```{r}
sessionInfo()
```
