---
title: "Making Tidy Data"
author:
- name: Martin Morgan
  affiliation: Roswell Park Cancer Institute, Buffalo, NY
output:
  BiocStyle::html_document:
    toc_float: true
package: BiocStyle
vignette: |
  %\VignetteIndexEntry{Working with Tidy Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(tidyverse)
library(magrittr)
```

# ALL

Phenotypic data. `%<>%`, `.`

```{r}
pdata = read_csv("~/extdata/ALL-phenoData.csv")
pdata %>% group_by(mol.biol) %>% summarize(n=n())
pdata %<>% filter(mol.biol %in% c("BCR/ABL", "NEG")) %>%
    mutate(mol.bio = factor(mol.biol))
pdata %>% t.test(age ~ mol.biol, .)
```

Expression data. `gather()`, `spread()`.

```{r}
exprs = read_csv("~/extdata/ALL-expression.csv")
exprs %<>% gather("Sample", "Exprssion", -1)
exprs %>% group_by(Gene) %>% summarize(Expression = mean(Expression))
## exprs %>% spread("Gene", "Expression")
```

Together. `*_join()`.

```{r}
all <- left_join(pdata, exprs)
```

# TCGA survival analysis

Setup: `install.packages(cgdsr)`

```{r}
library(tidyverse)
library(cgdsr)
url <- "http://www.cbioportal.org/public-portal/"
cbiop <- CGDS(url)

studies <- getCancerStudies(cbiop) %>% as.tibble()
## View(studies)
study <- "skcm_tcga"

cases <- getCaseLists(cbiop, study) %>% as.tibble()
## View(cases)
allcases <- "skcm_tcga_all"
mRNAcases <- "skcm_tcga_rna_seq_v2_mrna"

profiles <- getGeneticProfiles(cbiop, study) %>% as.tibble()
## View(profiles)
profile = "skcm_tcga_rna_seq_v2_mrna_median_Zscores"

genes <- c('CD63', 'CD9', 'CD81')
```

## Download

```{r}
mRNA <- getProfileData(cbiop, genes, profile, mRNAcases) %>%
    rownames_to_column("id") %>% as_tibble()

clinical <- getClinicalData(cbiop, allcases) %>%
    rownames_to_column("id") %>% as_tibble()
```

## Cleaning

```{r}
data <- full_join(clinical, mRNA)

clean <- data %>%
    filter(
        !is.na(CD63), !is.na(CD9), !is.na(CD81),
        SAMPLE_TYPE %in% c("Metastatic", "Primary Tumor"),
        nzchar(OS_STATUS)
    ) %>%
    select(
        id, SAMPLE_TYPE,
        OS_STATUS, OS_MONTHS,
        DFS_STATUS, DFS_MONTHS,
        CD63, CD9, CD81
    ) %>%
    mutate(
        SAMPLE_TYPE = factor(SAMPLE_TYPE),
        OS_STATUS = factor(OS_STATUS),
        DFS_STATUS = factor(DFS_STATUS)
    )

clean %>% summary()
```
